In [1]:
import pandas as pd
import numpy as np

In [7]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
b = np.ones((7,7))
b

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
c = np.full((5,5), 9)
c

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [14]:
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
e = np.random.random((7,4))
e

array([[0.13962606, 0.57538422, 0.26523777, 0.08341514],
       [0.32775803, 0.06422699, 0.19871592, 0.47215487],
       [0.14824895, 0.38466945, 0.1138402 , 0.18327198],
       [0.92837752, 0.01305033, 0.84458206, 0.63305136],
       [0.97532856, 0.73195993, 0.29942513, 0.42375172],
       [0.4231733 , 0.25822737, 0.53946497, 0.36514878],
       [0.79249097, 0.11622406, 0.74405896, 0.60777114]])

In [21]:
f = e[:5, :3]
f

array([[0.13962606, 0.57538422, 0.26523777],
       [0.32775803, 0.06422699, 0.19871592],
       [0.14824895, 0.38466945, 0.1138402 ],
       [0.92837752, 0.01305033, 0.84458206],
       [0.97532856, 0.73195993, 0.29942513]])

In [25]:
ar1 = np.random.random((3,3))
ar2 = np.random.random((3,3))
sum1 = np.add(ar1,ar2)
sum1

array([[0.52284088, 0.96882363, 1.11476652],
       [0.34054508, 0.95575071, 0.78634201],
       [1.46522908, 1.20427871, 1.43121762]])

In [33]:
ar1

array([[0.50752551, 0.09929863, 0.61866082],
       [0.09576642, 0.7680969 , 0.57031967],
       [0.72561213, 0.61054448, 0.59125202]])

In [34]:
ar2

array([[0.01531537, 0.869525  , 0.49610571],
       [0.24477866, 0.18765381, 0.21602235],
       [0.73961695, 0.59373423, 0.8399656 ]])

In [27]:
pro = np.multiply(ar1, ar2)
pro

array([[0.00777294, 0.08634264, 0.30692116],
       [0.02344158, 0.14413631, 0.12320179],
       [0.53667503, 0.36250115, 0.49663135]])

In [28]:
div = np.divide(ar1, ar2)
div2 = (ar1/ar2)
div

array([[33.13832061,  0.11419871,  1.24703427],
       [ 0.39123683,  4.09315908,  2.64009569],
       [ 0.98106477,  1.02831275,  0.70390027]])

In [29]:
div2

array([[33.13832061,  0.11419871,  1.24703427],
       [ 0.39123683,  4.09315908,  2.64009569],
       [ 0.98106477,  1.02831275,  0.70390027]])

In [31]:
ar1

array([[0.50752551, 0.09929863, 0.61866082],
       [0.09576642, 0.7680969 , 0.57031967],
       [0.72561213, 0.61054448, 0.59125202]])

In [30]:
np.sqrt(ar1)

array([[0.71240825, 0.31511685, 0.78654995],
       [0.30946151, 0.87641138, 0.75519512],
       [0.8518287 , 0.78137346, 0.76892914]])

In [32]:
ar1.dot(ar2)

array([[0.48965115, 0.82725999, 0.79289083],
       [0.61129851, 0.56602592, 0.69248527],
       [0.59786128, 1.09655544, 0.98850292]])

In [35]:
np.dot(ar1, ar2)

array([[0.48965115, 0.82725999, 0.79289083],
       [0.61129851, 0.56602592, 0.69248527],
       [0.59786128, 1.09655544, 0.98850292]])

In [37]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
v = np.empty_like(x)

In [38]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
y

array([1, 0, 1])

In [43]:
for i in range(4):
    v[i, :] = x[i, :] + y
v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [45]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
yy = np.tile(y, (4, 1))
yy

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [46]:
v = x + yy
v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [48]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
v = y + x
v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])