In [1]:
import pandas as pd
import numpy as np

In [2]:
 a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [3]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(5,8,3)

array([5. , 6.5, 8. ])

In [6]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

In [11]:
np.fromstring('25 30 35 40', dtype=np.int, sep=' ')

array([25, 30, 35, 40])

In [13]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.zeros_like(a)

array([0, 0, 0, 0, 0])

In [15]:
a.size

5

In [16]:
a.shape

(5,)

In [17]:
a.ndim

1

In [18]:
a.itemsize

4

In [19]:
a.dtype

dtype('int32')

In [20]:
a.nbytes #size of whole array

20

In [21]:
b = np.arange(1,9)
print(b)

[1 2 3 4 5 6 7 8]


In [29]:
b = b.reshape(2,4)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
b.swapaxes(0, 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])