In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
%matplotlib inline

In [6]:
df = load_digits()

In [8]:
df.data.shape

(1797, 64)

In [14]:
df.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [11]:
df.target.shape

(1797,)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.data, df.target, test_size = 0.25, random_state=7)

In [15]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression(max_iter=10000)

In [19]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [25]:
X_test

array([[ 0.,  0.,  0., ..., 15.,  5.,  0.],
       [ 0.,  0.,  2., ...,  5.,  0.,  0.],
       [ 0.,  0., 11., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  2.,  0.,  0.],
       [ 0.,  0.,  2., ...,  5.,  0.,  0.]])

In [26]:
X_test[0]

array([ 0.,  0.,  0., 10., 13.,  1.,  0.,  0.,  0.,  1., 11., 12.,  7.,
        0.,  0.,  0.,  0.,  2., 16., 12.,  0.,  0.,  0.,  0.,  0.,  4.,
       16., 11.,  0.,  0.,  0.,  0.,  0.,  4., 16., 15.,  8.,  4.,  0.,
        0.,  0.,  4., 16., 16., 13., 16.,  6.,  0.,  0.,  0.,  7., 16.,
        7., 13., 14.,  0.,  0.,  0.,  0.,  7., 15., 15.,  5.,  0.])

In [32]:
X_test[0].reshape(1,-1)

array([[ 0.,  0.,  0., 10., 13.,  1.,  0.,  0.,  0.,  1., 11., 12.,  7.,
         0.,  0.,  0.,  0.,  2., 16., 12.,  0.,  0.,  0.,  0.,  0.,  4.,
        16., 11.,  0.,  0.,  0.,  0.,  0.,  4., 16., 15.,  8.,  4.,  0.,
         0.,  0.,  4., 16., 16., 13., 16.,  6.,  0.,  0.,  0.,  7., 16.,
         7., 13., 14.,  0.,  0.,  0.,  0.,  7., 15., 15.,  5.,  0.]])

In [31]:
model.predict(X_test[0].reshape(1,-1))

array([6])